import { Meta, StoryObj } from '@storybook/react';
import XArrow from '..';
declare const meta: Meta<typeof XArrow>;
export default meta;
type Story = StoryObj<typeof XArrow>;
export declare const Right: Story;
export declare const PrimaryRight: Story;
export declare const SuccessRight: Story;
export declare const WarningRight: Story;
export declare const ErrorRight: Story;
export declare const DisabledRight: Story;
