import { Meta, StoryObj } from '@storybook/react';
import XArrow from '..';
declare const meta: Meta<typeof XArrow>;
export default meta;
type Story = StoryObj<typeof XArrow>;
export declare const Down: Story;
export declare const PrimaryDown: Story;
export declare const SuccessDown: Story;
export declare const WarningDown: Story;
export declare const ErrorDown: Story;
export declare const Disabled: Story;
