import { Meta, StoryObj } from '@storybook/react';
import XArrow from '..';
declare const meta: Meta<typeof XArrow>;
export default meta;
type Story = StoryObj<typeof XArrow>;
export declare const Left: Story;
export declare const PrimaryLeft: Story;
export declare const SuccessLeft: Story;
export declare const WarningLeft: Story;
export declare const ErrorLeft: Story;
export declare const DisabledLeft: Story;
