import { Meta, StoryObj } from '@storybook/react';
import XArrow from '..';
declare const meta: Meta<typeof XArrow>;
export default meta;
type Story = StoryObj<typeof XArrow>;
export declare const Up: Story;
export declare const PrimaryUp: Story;
export declare const SuccessUp: Story;
export declare const WarningUp: Story;
export declare const ErrorUp: Story;
export declare const DisabledUp: Story;
