import { Meta, StoryObj } from '@storybook/react';
import XCard from '..';
declare const meta: Meta<typeof XCard>;
export default meta;
type Story = StoryObj<typeof XCard>;
export declare const WithOnClick: Story;
export declare const PrimaryWithOnClick: Story;
export declare const SuccessWithOnClick: Story;
export declare const WarningWithOnClick: Story;
export declare const ErrorWithOnClick: Story;
export declare const DisabledWithOnClick: Story;
