import { Meta, StoryObj } from '@storybook/react';
import XCard from '..';
declare const meta: Meta<typeof XCard>;
export default meta;
type Story = StoryObj<typeof XCard>;
export declare const WithButton: Story;
export declare const PrimaryWithButton: Story;
export declare const SuccessWithButton: Story;
export declare const WarningWithButton: Story;
export declare const ErrorWithButton: Story;
export declare const DisabledWithButton: Story;
