import { Meta, StoryObj } from '@storybook/react';
import XCard from '..';
declare const meta: Meta<typeof XCard>;
export default meta;
type Story = StoryObj<typeof XCard>;
export declare const WithButtonAndOnClick: Story;
export declare const PrimaryButtonAndOnClick: Story;
export declare const SuccessButtonAndOnClick: Story;
export declare const WarningButtonAndOnClick: Story;
export declare const ErrorButtonAndOnClick: Story;
export declare const DisabledButtonAndOnClick: Story;
