import { Meta, StoryObj } from '@storybook/react';
import XCard from '..';
declare const meta: Meta<typeof XCard>;
export default meta;
type Story = StoryObj<typeof XCard>;
export declare const WithBadge: Story;
export declare const PrimaryWithBadge: Story;
export declare const SuccessWithBadge: Story;
export declare const WarningWithBadge: Story;
export declare const ErrorWithBadge: Story;
export declare const DisabledWithBadge: Story;
