import { Meta, StoryObj } from "@storybook/react";
import XText from "..";
declare const meta: Meta<typeof XText>;
export default meta;
type Story = StoryObj<typeof XText>;
export declare const Normal: Story;
export declare const Primary: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Disabled: Story;
