import { Meta, StoryObj } from "@storybook/react";
import XText from "..";
declare const meta: Meta<typeof XText>;
export default meta;
type Story = StoryObj<typeof XText>;
export declare const Uppercase: Story;
export declare const PrimaryUppercase: Story;
export declare const SuccessUppercase: Story;
export declare const WarningUppercase: Story;
export declare const ErrorUppercase: Story;
export declare const DisabledUppercase: Story;
