import { Meta, StoryObj } from "@storybook/react";
import XText from "..";
declare const meta: Meta<typeof XText>;
export default meta;
type Story = StoryObj<typeof XText>;
export declare const CenterBigger: Story;
export declare const PrimaryCenterBigger: Story;
export declare const SuccessCenterBigger: Story;
export declare const WarningCenterBigger: Story;
export declare const ErrorCenterBigger: Story;
export declare const DisabledCenterBigger: Story;
