import { Meta, StoryObj } from "@storybook/react";
import XText from "..";
declare const meta: Meta<typeof XText>;
export default meta;
type Story = StoryObj<typeof XText>;
export declare const BigCenterUppercase: Story;
export declare const PrimaryBigCenterUppercase: Story;
export declare const SuccessBigCenterUppercase: Story;
export declare const WarningBigCenterUppercase: Story;
export declare const ErrorBigCenterUppercase: Story;
export declare const DisabledBigCenterUppercase: Story;
