import { Meta, StoryObj } from "@storybook/react";
import XText from "..";
declare const meta: Meta<typeof XText>;
export default meta;
type Story = StoryObj<typeof XText>;
export declare const BiggerUppercase: Story;
export declare const PrimaryBiggerUppercase: Story;
export declare const SuccessBiggerUppercase: Story;
export declare const WarningBiggerUppercase: Story;
export declare const ErrorBiggerUppercase: Story;
export declare const DisaledBiggerUppercase: Story;
