import { Meta, StoryObj } from "@storybook/react";
import XText from "..";
declare const meta: Meta<typeof XText>;
export default meta;
type Story = StoryObj<typeof XText>;
export declare const BiggerCenterUppercase: Story;
export declare const PrimaryBiggerCenterUppercase: Story;
export declare const SuccessBiggerCenterUppercase: Story;
export declare const WarningBiggerCenterUppercase: Story;
export declare const ErrorBiggerCenterUppercase: Story;
export declare const DisaledBiggerCenterUppercase: Story;
