import { Meta, StoryObj } from '@storybook/react';
import XInput from '..';
declare const meta: Meta<typeof XInput>;
export default meta;
type Story = StoryObj<typeof XInput>;
export declare const Normal: Story;
export declare const Primary: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Disabled: Story;
