/// <reference types="react" />
export declare const colors: {
    black: string;
    blackLight: string;
    blackShadow: string;
    blackDark: string;
    gray: string;
    white: string;
    whiteLight: string;
    primary: string;
    primaryLight: string;
    primaryDark: string;
    primaryShadow: string;
    success: string;
    successLight: string;
    successDark: string;
    successShadow: string;
    warning: string;
    warningLight: string;
    warningDark: string;
    warningShadow: string;
    error: string;
    errorLight: string;
    errorDark: string;
    errorShadow: string;
    rose: string;
    usdt: string;
    disabled: string;
    disabledLight: string;
    disabledFont: string;
    disabledShadow: string;
};
declare const XColors: import("react").NamedExoticComponent<import("styled-components").ExecutionProps & object>;
export default XColors;
