import { Meta, StoryObj } from '@storybook/react';
import XButton from "..";
declare const meta: Meta<typeof XButton>;
export default meta;
type Story = StoryObj<typeof XButton>;
export declare const Normal: Story;
export declare const Primary: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Disabled: Story;
