import { Meta, StoryObj } from '@storybook/react';
import XBallon from '..';
declare const meta: Meta<typeof XBallon>;
export default meta;
type Story = StoryObj<typeof XBallon>;
export declare const Normal: Story;
export declare const Primary: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Disabled: Story;
