/// <reference types="react" />
/// <reference types="react" />
export declare const XArrow: import("styled-components").IStyledComponent<"web", {
    color?: string | undefined;
    content?: string | undefined;
    height?: string | number | undefined;
    translate?: "yes" | "no" | undefined;
    width?: string | number | undefined;
    slot?: string | undefined;
    style?: import("react").CSSProperties | undefined;
    title?: string | undefined;
    children?: import("react").ReactNode;
    onClick?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    key?: import("react").Key | null | undefined;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoFocus?: boolean | undefined;
    className?: string | undefined;
    contentEditable?: "inherit" | (boolean | "true" | "false") | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "true" | "false") | undefined;
    hidden?: boolean | undefined;
    id?: string | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    placeholder?: string | undefined;
    spellCheck?: (boolean | "true" | "false") | undefined;
    tabIndex?: number | undefined;
    radioGroup?: string | undefined;
    role?: import("react").AriaRole | undefined;
    about?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCapitalize?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "on" | "off" | undefined;
    inputMode?: "none" | "search" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | undefined;
    is?: string | undefined;
    'aria-activedescendant'?: string | undefined;
    'aria-atomic'?: (boolean | "true" | "false") | undefined;
    'aria-autocomplete'?: "none" | "list" | "inline" | "both" | undefined;
    'aria-braillelabel'?: string | undefined;
    'aria-brailleroledescription'?: string | undefined;
    'aria-busy'?: (boolean | "true" | "false") | undefined;
    'aria-checked'?: boolean | "true" | "false" | "mixed" | undefined;
    'aria-colcount'?: number | undefined;
    'aria-colindex'?: number | undefined;
    'aria-colindextext'?: string | undefined;
    'aria-colspan'?: number | undefined;
    'aria-controls'?: string | undefined;
    'aria-current'?: boolean | "page" | "time" | "true" | "false" | "step" | "location" | "date" | undefined;
    'aria-describedby'?: string | undefined;
    'aria-description'?: string | undefined;
    'aria-details'?: string | undefined;
    'aria-disabled'?: (boolean | "true" | "false") | undefined;
    'aria-dropeffect'?: "none" | "link" | "copy" | "execute" | "move" | "popup" | undefined;
    'aria-errormessage'?: string | undefined;
    'aria-expanded'?: (boolean | "true" | "false") | undefined;
    'aria-flowto'?: string | undefined;
    'aria-grabbed'?: (boolean | "true" | "false") | undefined;
    'aria-haspopup'?: boolean | "grid" | "dialog" | "menu" | "true" | "false" | "listbox" | "tree" | undefined;
    'aria-hidden'?: (boolean | "true" | "false") | undefined;
    'aria-invalid'?: boolean | "true" | "false" | "grammar" | "spelling" | undefined;
    'aria-keyshortcuts'?: string | undefined;
    'aria-label'?: string | undefined;
    'aria-labelledby'?: string | undefined;
    'aria-level'?: number | undefined;
    'aria-live'?: "off" | "assertive" | "polite" | undefined;
    'aria-modal'?: (boolean | "true" | "false") | undefined;
    'aria-multiline'?: (boolean | "true" | "false") | undefined;
    'aria-multiselectable'?: (boolean | "true" | "false") | undefined;
    'aria-orientation'?: "horizontal" | "vertical" | undefined;
    'aria-owns'?: string | undefined;
    'aria-placeholder'?: string | undefined;
    'aria-posinset'?: number | undefined;
    'aria-pressed'?: boolean | "true" | "false" | "mixed" | undefined;
    'aria-readonly'?: (boolean | "true" | "false") | undefined;
    'aria-relevant'?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    'aria-required'?: (boolean | "true" | "false") | undefined;
    'aria-roledescription'?: string | undefined;
    'aria-rowcount'?: number | undefined;
    'aria-rowindex'?: number | undefined;
    'aria-rowindextext'?: string | undefined;
    'aria-rowspan'?: number | undefined;
    'aria-selected'?: (boolean | "true" | "false") | undefined;
    'aria-setsize'?: number | undefined;
    'aria-sort'?: "none" | "ascending" | "descending" | "other" | undefined;
    'aria-valuemax'?: number | undefined;
    'aria-valuemin'?: number | undefined;
    'aria-valuenow'?: number | undefined;
    'aria-valuetext'?: string | undefined;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
    onCopyCapture?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
    onCut?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
    onCutCapture?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
    onPaste?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
    onPasteCapture?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
    onCompositionEnd?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
    onCompositionEndCapture?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
    onCompositionStart?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
    onCompositionStartCapture?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
    onCompositionUpdate?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
    onCompositionUpdateCapture?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
    onFocus?: import("react").FocusEventHandler<HTMLImageElement> | undefined;
    onFocusCapture?: import("react").FocusEventHandler<HTMLImageElement> | undefined;
    onBlur?: import("react").FocusEventHandler<HTMLImageElement> | undefined;
    onBlurCapture?: import("react").FocusEventHandler<HTMLImageElement> | undefined;
    onChange?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onChangeCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onBeforeInput?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onBeforeInputCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onInput?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onInputCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onReset?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onResetCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onSubmit?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onSubmitCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onInvalid?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onInvalidCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
    onLoad?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onLoadCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onError?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onErrorCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onKeyDown?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
    onKeyDownCapture?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
    onKeyPress?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
    onKeyPressCapture?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
    onKeyUp?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
    onKeyUpCapture?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
    onAbort?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onAbortCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onCanPlay?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onCanPlayCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onCanPlayThrough?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onCanPlayThroughCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onDurationChange?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onDurationChangeCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onEmptied?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onEmptiedCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onEncrypted?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onEncryptedCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onEnded?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onEndedCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onLoadedData?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onLoadedDataCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onLoadedMetadata?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onLoadedMetadataCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onLoadStart?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onLoadStartCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onPause?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onPauseCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onPlay?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onPlayCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onPlaying?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onPlayingCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onProgress?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onProgressCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onRateChange?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onRateChangeCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onResize?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onResizeCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onSeeked?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onSeekedCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onSeeking?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onSeekingCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onStalled?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onStalledCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onSuspend?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onSuspendCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onTimeUpdate?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onTimeUpdateCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onVolumeChange?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onVolumeChangeCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onWaiting?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onWaitingCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onAuxClick?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onAuxClickCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onClickCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onContextMenu?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onContextMenuCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onDoubleClick?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onDoubleClickCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onDrag?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragEnd?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragEndCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragEnter?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragEnterCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragExit?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragExitCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragLeave?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragLeaveCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragOver?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragOverCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragStart?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDragStartCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDrop?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onDropCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
    onMouseDown?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseDownCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseEnter?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseLeave?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseMove?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseMoveCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseOut?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseOutCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseOver?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseOverCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseUp?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onMouseUpCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
    onSelect?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onSelectCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
    onTouchCancel?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
    onTouchCancelCapture?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
    onTouchEnd?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
    onTouchEndCapture?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
    onTouchMove?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
    onTouchMoveCapture?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
    onTouchStart?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
    onTouchStartCapture?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
    onPointerDown?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerDownCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerMove?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerMoveCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerUp?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerUpCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerCancel?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerCancelCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerEnter?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerEnterCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerLeave?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerLeaveCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerOver?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerOverCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerOut?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onPointerOutCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onGotPointerCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onGotPointerCaptureCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onLostPointerCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onLostPointerCaptureCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
    onScroll?: import("react").UIEventHandler<HTMLImageElement> | undefined;
    onScrollCapture?: import("react").UIEventHandler<HTMLImageElement> | undefined;
    onWheel?: import("react").WheelEventHandler<HTMLImageElement> | undefined;
    onWheelCapture?: import("react").WheelEventHandler<HTMLImageElement> | undefined;
    onAnimationStart?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
    onAnimationStartCapture?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
    onAnimationEnd?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
    onAnimationEndCapture?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
    onAnimationIteration?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
    onAnimationIterationCapture?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
    onTransitionEnd?: import("react").TransitionEventHandler<HTMLImageElement> | undefined;
    onTransitionEndCapture?: import("react").TransitionEventHandler<HTMLImageElement> | undefined;
    crossOrigin?: "" | "anonymous" | "use-credentials" | undefined;
    referrerPolicy?: import("react").HTMLAttributeReferrerPolicy | undefined;
    sizes?: string | undefined;
    alt?: string | undefined;
    src?: string | undefined;
    loading?: "eager" | "lazy" | undefined;
    decoding?: "async" | "auto" | "sync" | undefined;
    srcSet?: string | undefined;
    useMap?: string | undefined;
    ref?: ((instance: HTMLImageElement | null) => void) | import("react").RefObject<HTMLImageElement> | null | undefined;
    right?: boolean | undefined;
    down?: boolean | undefined;
    left?: boolean | undefined;
    up?: boolean | undefined;
}>;
declare const S: {
    XArrow: import("styled-components").IStyledComponent<"web", {
        color?: string | undefined;
        content?: string | undefined;
        height?: string | number | undefined;
        translate?: "yes" | "no" | undefined;
        width?: string | number | undefined;
        slot?: string | undefined;
        style?: import("react").CSSProperties | undefined;
        title?: string | undefined;
        children?: import("react").ReactNode;
        onClick?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        key?: import("react").Key | null | undefined;
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: "inherit" | (boolean | "true" | "false") | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        placeholder?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        tabIndex?: number | undefined;
        radioGroup?: string | undefined;
        role?: import("react").AriaRole | undefined;
        about?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCapitalize?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "search" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | undefined;
        is?: string | undefined;
        'aria-activedescendant'?: string | undefined;
        'aria-atomic'?: (boolean | "true" | "false") | undefined;
        'aria-autocomplete'?: "none" | "list" | "inline" | "both" | undefined;
        'aria-braillelabel'?: string | undefined;
        'aria-brailleroledescription'?: string | undefined;
        'aria-busy'?: (boolean | "true" | "false") | undefined;
        'aria-checked'?: boolean | "true" | "false" | "mixed" | undefined;
        'aria-colcount'?: number | undefined;
        'aria-colindex'?: number | undefined;
        'aria-colindextext'?: string | undefined;
        'aria-colspan'?: number | undefined;
        'aria-controls'?: string | undefined;
        'aria-current'?: boolean | "page" | "time" | "true" | "false" | "step" | "location" | "date" | undefined;
        'aria-describedby'?: string | undefined;
        'aria-description'?: string | undefined;
        'aria-details'?: string | undefined;
        'aria-disabled'?: (boolean | "true" | "false") | undefined;
        'aria-dropeffect'?: "none" | "link" | "copy" | "execute" | "move" | "popup" | undefined;
        'aria-errormessage'?: string | undefined;
        'aria-expanded'?: (boolean | "true" | "false") | undefined;
        'aria-flowto'?: string | undefined;
        'aria-grabbed'?: (boolean | "true" | "false") | undefined;
        'aria-haspopup'?: boolean | "grid" | "dialog" | "menu" | "true" | "false" | "listbox" | "tree" | undefined;
        'aria-hidden'?: (boolean | "true" | "false") | undefined;
        'aria-invalid'?: boolean | "true" | "false" | "grammar" | "spelling" | undefined;
        'aria-keyshortcuts'?: string | undefined;
        'aria-label'?: string | undefined;
        'aria-labelledby'?: string | undefined;
        'aria-level'?: number | undefined;
        'aria-live'?: "off" | "assertive" | "polite" | undefined;
        'aria-modal'?: (boolean | "true" | "false") | undefined;
        'aria-multiline'?: (boolean | "true" | "false") | undefined;
        'aria-multiselectable'?: (boolean | "true" | "false") | undefined;
        'aria-orientation'?: "horizontal" | "vertical" | undefined;
        'aria-owns'?: string | undefined;
        'aria-placeholder'?: string | undefined;
        'aria-posinset'?: number | undefined;
        'aria-pressed'?: boolean | "true" | "false" | "mixed" | undefined;
        'aria-readonly'?: (boolean | "true" | "false") | undefined;
        'aria-relevant'?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
        'aria-required'?: (boolean | "true" | "false") | undefined;
        'aria-roledescription'?: string | undefined;
        'aria-rowcount'?: number | undefined;
        'aria-rowindex'?: number | undefined;
        'aria-rowindextext'?: string | undefined;
        'aria-rowspan'?: number | undefined;
        'aria-selected'?: (boolean | "true" | "false") | undefined;
        'aria-setsize'?: number | undefined;
        'aria-sort'?: "none" | "ascending" | "descending" | "other" | undefined;
        'aria-valuemax'?: number | undefined;
        'aria-valuemin'?: number | undefined;
        'aria-valuenow'?: number | undefined;
        'aria-valuetext'?: string | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
        onCopyCapture?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
        onCut?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
        onCutCapture?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
        onPaste?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
        onPasteCapture?: import("react").ClipboardEventHandler<HTMLImageElement> | undefined;
        onCompositionEnd?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
        onCompositionEndCapture?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
        onCompositionStart?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
        onCompositionStartCapture?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
        onCompositionUpdate?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
        onCompositionUpdateCapture?: import("react").CompositionEventHandler<HTMLImageElement> | undefined;
        onFocus?: import("react").FocusEventHandler<HTMLImageElement> | undefined;
        onFocusCapture?: import("react").FocusEventHandler<HTMLImageElement> | undefined;
        onBlur?: import("react").FocusEventHandler<HTMLImageElement> | undefined;
        onBlurCapture?: import("react").FocusEventHandler<HTMLImageElement> | undefined;
        onChange?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onChangeCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onBeforeInput?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onBeforeInputCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onInput?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onInputCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onReset?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onResetCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onSubmit?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onSubmitCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onInvalid?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onInvalidCapture?: import("react").FormEventHandler<HTMLImageElement> | undefined;
        onLoad?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onLoadCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onError?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onErrorCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onKeyDown?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
        onKeyDownCapture?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
        onKeyPress?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
        onKeyPressCapture?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
        onKeyUp?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
        onKeyUpCapture?: import("react").KeyboardEventHandler<HTMLImageElement> | undefined;
        onAbort?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onAbortCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onCanPlay?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onCanPlayCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onCanPlayThrough?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onCanPlayThroughCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onDurationChange?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onDurationChangeCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onEmptied?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onEmptiedCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onEncrypted?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onEncryptedCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onEnded?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onEndedCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onLoadedData?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onLoadedDataCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onLoadedMetadata?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onLoadedMetadataCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onLoadStart?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onLoadStartCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onPause?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onPauseCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onPlay?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onPlayCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onPlaying?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onPlayingCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onProgress?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onProgressCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onRateChange?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onRateChangeCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onResize?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onResizeCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onSeeked?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onSeekedCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onSeeking?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onSeekingCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onStalled?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onStalledCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onSuspend?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onSuspendCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onTimeUpdate?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onTimeUpdateCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onVolumeChange?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onVolumeChangeCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onWaiting?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onWaitingCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onAuxClick?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onAuxClickCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onClickCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onContextMenu?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onContextMenuCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onDoubleClick?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onDoubleClickCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onDrag?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragEnd?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragEndCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragEnter?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragEnterCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragExit?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragExitCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragLeave?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragLeaveCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragOver?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragOverCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragStart?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDragStartCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDrop?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onDropCapture?: import("react").DragEventHandler<HTMLImageElement> | undefined;
        onMouseDown?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseDownCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseEnter?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseLeave?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseMove?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseMoveCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseOut?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseOutCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseOver?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseOverCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseUp?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onMouseUpCapture?: import("react").MouseEventHandler<HTMLImageElement> | undefined;
        onSelect?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onSelectCapture?: import("react").ReactEventHandler<HTMLImageElement> | undefined;
        onTouchCancel?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
        onTouchCancelCapture?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
        onTouchEnd?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
        onTouchEndCapture?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
        onTouchMove?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
        onTouchMoveCapture?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
        onTouchStart?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
        onTouchStartCapture?: import("react").TouchEventHandler<HTMLImageElement> | undefined;
        onPointerDown?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerDownCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerMove?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerMoveCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerUp?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerUpCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerCancel?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerCancelCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerEnter?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerEnterCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerLeave?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerLeaveCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerOver?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerOverCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerOut?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onPointerOutCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onGotPointerCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onGotPointerCaptureCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onLostPointerCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onLostPointerCaptureCapture?: import("react").PointerEventHandler<HTMLImageElement> | undefined;
        onScroll?: import("react").UIEventHandler<HTMLImageElement> | undefined;
        onScrollCapture?: import("react").UIEventHandler<HTMLImageElement> | undefined;
        onWheel?: import("react").WheelEventHandler<HTMLImageElement> | undefined;
        onWheelCapture?: import("react").WheelEventHandler<HTMLImageElement> | undefined;
        onAnimationStart?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
        onAnimationStartCapture?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
        onAnimationEnd?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
        onAnimationEndCapture?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
        onAnimationIteration?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
        onAnimationIterationCapture?: import("react").AnimationEventHandler<HTMLImageElement> | undefined;
        onTransitionEnd?: import("react").TransitionEventHandler<HTMLImageElement> | undefined;
        onTransitionEndCapture?: import("react").TransitionEventHandler<HTMLImageElement> | undefined;
        crossOrigin?: "" | "anonymous" | "use-credentials" | undefined;
        referrerPolicy?: import("react").HTMLAttributeReferrerPolicy | undefined;
        sizes?: string | undefined;
        alt?: string | undefined;
        src?: string | undefined;
        loading?: "eager" | "lazy" | undefined;
        decoding?: "async" | "auto" | "sync" | undefined;
        srcSet?: string | undefined;
        useMap?: string | undefined;
        ref?: ((instance: HTMLImageElement | null) => void) | import("react").RefObject<HTMLImageElement> | null | undefined;
        right?: boolean | undefined;
        down?: boolean | undefined;
        left?: boolean | undefined;
        up?: boolean | undefined;
    }>;
};
export default S;
