import { Meta, StoryObj } from '@storybook/react';
import XLabel from '.';
declare const meta: Meta<typeof XLabel>;
export default meta;
type Story = StoryObj<typeof XLabel>;
export declare const Normal: Story;
export declare const Primary: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Disabled: Story;
