import { Meta, StoryObj } from '@storybook/react';
import XAlert from '..';
declare const meta: Meta<typeof XAlert>;
export default meta;
type Story = StoryObj<typeof XAlert>;
export declare const WithError: Story;
export declare const PrimaryWithError: Story;
export declare const SuccessWithError: Story;
export declare const WarningWithError: Story;
export declare const ErrorWithError: Story;
export declare const DiabledWithError: Story;
