import { Meta, StoryObj } from '@storybook/react';
import XAlert from '..';
declare const meta: Meta<typeof XAlert>;
export default meta;
type Story = StoryObj<typeof XAlert>;
export declare const WithoutCloseIconComponent: Story;
export declare const PrimaryWithoutCloseComponent: Story;
export declare const SuccessWithoutCloseComponent: Story;
export declare const WarningWithoutCloseComponent: Story;
export declare const ErrorWithoutCloseComponent: Story;
export declare const DisableWithoutClosed: Story;
