import { Meta, StoryObj } from '@storybook/react';
import XAvatar from '.';
declare const meta: Meta<typeof XAvatar>;
export default meta;
type Story = StoryObj<typeof XAvatar>;
export declare const Normal: Story;
export declare const Primary: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Disabled: Story;
