import { Meta, StoryObj } from '@storybook/react';
import XBadges from '..';
declare const meta: Meta<typeof XBadges>;
export default meta;
type Story = StoryObj<typeof XBadges>;
export declare const WithLabel: Story;
export declare const PrimaryWithLabel: Story;
export declare const SuccessWithLabel: Story;
export declare const WarningWithLabel: Story;
export declare const ErrorWithLabel: Story;
export declare const DisabledWithLabel: Story;
