import { Meta, StoryObj } from '@storybook/react';
import XButton from "..";
declare const meta: Meta<typeof XButton>;
export default meta;
type Story = StoryObj<typeof XButton>;
export declare const NormalFull: Story;
export declare const PrimaryFull: Story;
export declare const SuccessFull: Story;
export declare const WarningFull: Story;
export declare const ErrorFull: Story;
export declare const DisabledFull: Story;
