import { Meta, StoryObj } from '@storybook/react';
import XBallon from '..';
declare const meta: Meta<typeof XBallon>;
export default meta;
type Story = StoryObj<typeof XBallon>;
export declare const Full: Story;
export declare const PrimaryFull: Story;
export declare const SuccessFull: Story;
export declare const WarningFull: Story;
export declare const ErrorFull: Story;
export declare const DisabledFull: Story;
