import { Meta, StoryObj } from '@storybook/react';
import XBalloon from '..';
declare const meta: Meta<typeof XBalloon>;
export default meta;
type Story = StoryObj<typeof XBalloon>;
export declare const Normal: Story;
export declare const Primary: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Disabled: Story;
