import { Meta, StoryObj } from '@storybook/react';
import XLine from '..';
declare const meta: Meta<typeof XLine>;
export default meta;
type Story = StoryObj<typeof XLine>;
export declare const WithMargin: Story;
export declare const PrimaryMargin: Story;
export declare const SuccessMargin: Story;
export declare const WarningMargin: Story;
export declare const ErrorMargin: Story;
export declare const DisabledMargin: Story;
