import { Meta, StoryObj } from '@storybook/react';
import XFieldset from '..';
declare const meta: Meta<typeof XFieldset>;
export default meta;
type Story = StoryObj<typeof XFieldset>;
export declare const Input: Story;
export declare const PrimaryInput: Story;
export declare const SuccessInput: Story;
export declare const WarningInput: Story;
export declare const ErrorInput: Story;
export declare const DisabledInput: Story;
