import { Meta, StoryObj } from "@storybook/react";
import XContainer from "..";
declare const meta: Meta<typeof XContainer>;
export default meta;
type Story = StoryObj<typeof XContainer>;
export declare const Simple: Story;
export declare const PrimarySimple: Story;
export declare const SuccessSimple: Story;
export declare const WarningSimple: Story;
export declare const ErrorSimple: Story;
export declare const DisabledSimple: Story;
