import { Meta, StoryObj } from "@storybook/react";
import XContainer from "..";
declare const meta: Meta<typeof XContainer>;
export default meta;
type Story = StoryObj<typeof XContainer>;
export declare const FullWithTitle: Story;
export declare const PrimaryFullWithTitle: Story;
export declare const SuccessFullWithTitle: Story;
export declare const WarningFullWithTitle: Story;
export declare const ErrorFullWithTitle: Story;
export declare const DisabledFullWithTitle: Story;
