import { Meta, StoryObj } from "@storybook/react";
import XContainer from "..";
declare const meta: Meta<typeof XContainer>;
export default meta;
type Story = StoryObj<typeof XContainer>;
export declare const FullWithTitleCenter: Story;
export declare const PrimaryFullWithTitleCenter: Story;
export declare const SuccessFullWithTitleCenter: Story;
export declare const WarningFullWithTitleCenter: Story;
export declare const ErrorFullWithTitleCenter: Story;
export declare const DisabledFullWithTitleCenter: Story;
