import { Meta, StoryObj } from "@storybook/react";
import XContainer from "..";
declare const meta: Meta<typeof XContainer>;
export default meta;
type Story = StoryObj<typeof XContainer>;
export declare const WithTitle: Story;
export declare const PrimaryWithTitle: Story;
export declare const SuccessWithTitle: Story;
export declare const WarningWithTitle: Story;
export declare const ErrorWithTitle: Story;
export declare const DisabledWithTitle: Story;
