import { Meta, StoryObj } from "@storybook/react";
import XContainer from "..";
declare const meta: Meta<typeof XContainer>;
export default meta;
type Story = StoryObj<typeof XContainer>;
export declare const WithTitleCenter: Story;
export declare const PrimaryWithTitleCenter: Story;
export declare const SuccessWithTitleCenter: Story;
export declare const WarningWithTitleCenter: Story;
export declare const ErrorWithTitleCenter: Story;
export declare const DisabledWithTitleCenter: Story;
