import { Meta, StoryObj } from "@storybook/react";
import XContainer from "..";
declare const meta: Meta<typeof XContainer>;
export default meta;
type Story = StoryObj<typeof XContainer>;
export declare const BorderAnimation: Story;
export declare const PrimaryBorderAnimation: Story;
export declare const SuccessBorderAnimation: Story;
export declare const WarningBorderAnimation: Story;
export declare const ErrorBorderAnimation: Story;
export declare const DisabledBorderAnimation: Story;
